version: "3"
services:
  app:
    image: ilyakarachun/ivashin
    container_name: container-ivashinApp
    build: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: postgres
    container_name: container-postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${PASSWORD_DB}
      POSTGRES_USER: ${USER_DB}
      POSTGRES_DB: ${NAME_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
